<a href="https://colab.research.google.com/github/adriyennKB/Linear-Algebra-58019/blob/main/Application.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
import numpy as np
from scipy.linalg import solve
A = np.array([[20,10],[17,22]]) #Creation of 2x2 Matrix
B = np.array([[350],[500]]) #Creation of Matrix

#to print
print(A)
print()
print(B)
print()

X= np.linalg.solve(A,B) #way to solve 
print(X)

X= solve(A,B) #solving using scipy library
print()
print(X)

[[20 10]
 [17 22]]

[[350]
 [500]]

[[10.]
 [15.]]

[[10.]
 [15.]]


In [6]:
inv_A = np.linalg.inv(A) #To inverse A
print(inv_A)

X = np.linalg.inv(A).dot(B) #dot product of Inv of A and B
print(X)

[[ 0.08148148 -0.03703704]
 [-0.06296296  0.07407407]]
[[10.]
 [15.]]


In [7]:
X = np.dot(inv_A,B) #Checking
X

array([[10.],
       [15.]])

##Solving for three linear equations with unknown variables of x, y, and z

In [21]:
#4x+3y+2z=25
#-2x-2y+3z=-10
# 3x-5y+2z=-4

A= np.array([[4,3,2],[-2,2,3],[3,-5,2]]) #Creation of 3x3 Matrix
B= np.array([[25],[-10],[-4]]) #Creation of Matrix

#To Print
print(A)
print(B)
X= solve(A,B) #Solving using scipy
print("The Solution is:")
print(X)

[[ 4  3  2]
 [-2  2  3]
 [ 3 -5  2]]
[[ 25]
 [-10]
 [ -4]]
The Solution is:
[[ 5.]
 [ 3.]
 [-2.]]
