<a href="https://colab.research.google.com/github/adriyennKB/Linear-Algebra-58019/blob/main/Coding_Activity_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Coding Activity 3

In [6]:
import numpy as np 

X = np.array([[4,10,8],[10,26,26],[8,26,61]]) #creation of Matrix X
y = np.array([[44],[128],[214]]) #creation of Matix y

inv_X = np.linalg.inv(X) #to Inverse the Matrix X
b = np.linalg.inv(X).dot(y) #To get dot product of Inverse of X and y
c = np.dot(inv_X,y) #to compute for the dot product of Inv of A and B /Other way
print(X)

#to print or display
print(X)
print()
print(inv_X)
print()
print(y)
print()
print(b)
print()
print(c)

[[ 4 10  8]
 [10 26 26]
 [ 8 26 61]]
[[ 4 10  8]
 [10 26 26]
 [ 8 26 61]]

[[ 25.27777778 -11.16666667   1.44444444]
 [-11.16666667   5.          -0.66666667]
 [  1.44444444  -0.66666667   0.11111111]]

[[ 44]
 [128]
 [214]]

[[-8.]
 [ 6.]
 [ 2.]]

[[-8.]
 [ 6.]
 [ 2.]]


###To Check

In [7]:
d= np.dot(X,c)
print(d)

[[ 44.]
 [128.]
 [214.]]
