<a href="https://colab.research.google.com/github/adriyennKB/Linear-Algebra-58019/blob/main/Determinant_of_Matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Write a Python code to show as its solution. Save it as "Determinant of Matrix" in your GitHub repository.

In [6]:
import numpy as np #numerical method of Python
A = np.array([[1,2,-1],[4,6,-2],[-1,3,3]]) #declare the values of matrix
print(A) #to print Matrix A
print('\nThe Determinant of A is:')
print(round(np.linalg.det(A))) #To display the final answer of determinant of A and rounded off

[[ 1  2 -1]
 [ 4  6 -2]
 [-1  3  3]]

The Determinant of A is:
-14
