<a href="https://colab.research.google.com/github/adriyennKB/Linear-Algebra-58019/blob/main/Eigenvalue_and_Eigenvector.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np  #Import Library
from numpy.linalg import eig
#from scipy.linalg import solve

In [ ]:
A = np.array([[-12, 3],[4, 1]]) # create matrix A
print(f'Matrix A:\n {A}') # print matrix A

inv_A = np.linalg.inv(A)  #inverse of matrix A
print(f'\nInverse of Matrix A:\n{inv_A}') #print the inverse of matrix A

B = np.array([[0],[0]]) #create matrix B
print(f'\nMatrix B:\n {B}') #print matrix B

X = np.dot(inv_A, B) #dot product of the inverse of matrix A and matrix B
print(f'\nDot product:\n{X}') #print the solved dot product - wrong

Matrix A:
 [[-12   3]
 [  4   1]]

Inverse of Matrix A:
[[-0.04166667  0.125     ]
 [ 0.16666667  0.5       ]]

Matrix B:
 [[0]
 [0]]

Dot product:
[[0.]
 [0.]]


##Example 1


In [ ]:
A = np.array([[-6,3],[4,5]]) #creation of Matrix
print(f'Matrix A:\n{A}') #to print or display

w,v = np.linalg.eig(A) # use the eig method in order to get the eigenvalue and eigenvector of a square matrix A
#to print or display the eigenvalues and eigenvectors
print(f'The eigenvalue/s is/are:\n {w}')
print(f'The right eigenvectors are:\n {v}')
#x = v.round()
#print(x) # print the rounded eigenvectors

Matrix A:
[[-6  3]
 [ 4  5]]
The eigenvalue/s is/are:
 [-7.  6.]
The right eigenvectors are:
 [[-0.9486833  -0.24253563]
 [ 0.31622777 -0.9701425 ]]


##Example 2

In [ ]:
A = np.array([[2,2,4],[1,3,5],[2,3,4]]) #Creation of Matrix A
print(A) #to print or display
s,t = np.linalg.eig(A) # use the eig method in order to get the eigenvalue and eigenvector of a square matrix A
#print or display eigenvalues and eigenvectors
print(f'\nThe Eigenvalue/s is/are: {s.round()}')
print(f'\nThe right Eigenvectors are: \n{t.round()}\n')
c = np.dot(A,t.round()) #dot product of A and t
print(c) #to print or display

[[2 2 4]
 [1 3 5]
 [2 3 4]]

The Eigenvalue/s is/are: [ 9.  1. -1.]

The right Eigenvectors are: 
[[-1. -1. -0.]
 [-1.  1. -1.]
 [-1. -0.  1.]]

[[-8.  0.  2.]
 [-9.  2.  2.]
 [-9.  1.  1.]]
