<a href="https://colab.research.google.com/github/adriyennKB/Linear-Algebra-58019/blob/main/Final_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###Problem 1 Student A, Student B, and Student C have a total of Php 89 cash in their banks. Student A has 6 less than Student C. Student B has 3 times what Student C has. How much does each student have?

In [43]:
import numpy as np #Matrix Operator

e1= np.array([[1,1,1],[1,0,4],[0,0,5]]) #creation of Matrix e1
e2= np.array([[89],[89],[95]]) #creation of Matrix e2
amnt= np.linalg.inv(e1).dot(e2) #solve using dot and inv of Matrix e1 and e2
print(amnt) #to display or print

[[13.]
 [57.]
 [19.]]


###Problem 2: 3x - y + z = 5, 9x - 3y +3z = 15, -12x +4y -4z = -20

###Explanation: By means of using just the np.linalg.inv, the code itself will result to an error message that says that it is a singular matrix
###Also, since the matrix is singular due to the determinant is zero, so it will not be possible to inverse it.
###So by means of using pseudo inverse of A or the approximate initial matrix, the code will go through/run.

In [45]:
#Here i tried coding it by using pseudo inverse
import numpy as np
A= np.array([[3,-1,1],[9,-3,3],[-12,4,-4]]) #creation of Matrix A
print(f'Matrix A: \n {A}') #to display or print

pinv_A= np.linalg.pinv(A) #to compute the pseudo inverse of A
#Explanation: By means of using just the np.linalg.inv, the code itself will result to an error message that says that it is a singular matrix
#Also, since the matrix is singular due to the determinant is zero, so it will not be possible to inverse it.
#So by means of using pseudo inverse of A or the approximate initial matrix, the code will go through/run.
print(f'\nInverse of A: \n {A}') #to display or print

B= np.array([[5],[15],[-20]]) #creation of Matrix B
print(f'\nMatrix B:\n {B}\n') #to display or print

X= np.dot(pinv_A,B) #to compute for the dot product of Inverse of A ang B
print(X) #to display or print

Matrix A: 
 [[  3  -1   1]
 [  9  -3   3]
 [-12   4  -4]]

Inverse of A: 
 [[  3  -1   1]
 [  9  -3   3]
 [-12   4  -4]]

Matrix B:
 [[  5]
 [ 15]
 [-20]]

[[ 1.36363636]
 [-0.45454545]
 [ 0.45454545]]


###Problem 3  Consider the matrix

In [6]:
import numpy as np
from numpy.linalg import eig

A = np.array([[8,5,-6],[-12,-9,12],[-3,-3,5]]) #Creation of Matrix A
print(A) #to print or display
s,t = np.linalg.eig(A) # use the eig method in order to get the eigenvalue and eigenvector of a square matrix A
#print or display eigenvalues and eigenvectors
print(f'\nThe Eigenvalue/s is/are: {s.round()}')
print(f'\nThe right Eigenvectors are: \n{t}')
print(f'OR: \n{t.round()}\n') #rounded off version of the right Eigenvectors


[[  8   5  -6]
 [-12  -9  12]
 [ -3  -3   5]]

The Eigenvalue/s is/are: [-1.  3.  2.]

The right Eigenvectors are: 
[[ 3.01511345e-01 -7.07106781e-01  7.07106781e-01]
 [-9.04534034e-01  7.07106781e-01  1.53837015e-15]
 [-3.01511345e-01 -2.26120075e-15  7.07106781e-01]]
OR: 
[[ 0. -1.  1.]
 [-1.  1.  0.]
 [-0. -0.  1.]]

