<a href="https://colab.research.google.com/github/adriyennKB/Linear-Algebra-58019/blob/main/Midterm_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###Question 1. Create a Python code that displays a square matrix whose length is 5

In [4]:
import numpy as np #Import Library
#squarematrix that will display a length of 5 has the same length and width so 5x5
SquareMatrix= np.array([[1,2,3,4,5],[2,0,0,0,0],[3,0,0,0,0], [4,0,0,0,0], [5,0,0,0,0]]) #5x5 Matrix
print("Square Matrix whose length is 5 is")
print(SquareMatrix) #display final answer

Square Matrix whose length is 5 is
[[1 2 3 4 5]
 [2 0 0 0 0]
 [3 0 0 0 0]
 [4 0 0 0 0]
 [5 0 0 0 0]]


###Question 2. Create a Python code that displays a square matrix whose elements below the principal diagonal are zero (10 points)

In [40]:
triangularMatrix = np.array([[1,2,3,4],[0,5,6,7],[0,0,8,9],[0,0,0,10]]) #3x3 Matrix
#to print or display
print('A square matrix whose elements below the principal diagonal are zero:') 
print(triangularMatrix) #To print or display final answer

A square matrix whose elements below the principal diagonal are zero: 
[[ 1  2  3  4]
 [ 0  5  6  7]
 [ 0  0  8  9]
 [ 0  0  0 10]]


###Question 3. Create a Python code that displays a square matrix which is symmetrical (10 points)

In [28]:
squareMatrix= np.array ([[1,2,3,4,5],[2,1,2,3,4],[3,2,1,2,3],[4,3,2,1,2],[5,4,3,2,1]]) #Creates a square matrix that is symmetrical
#prints a square matrix which is symmetrical
print('A symmetrical Square Matrix')
print(squareMatrix)

A symmetrical Square Matrix
[[1 2 3 4 5]
 [2 1 2 3 4]
 [3 2 1 2 3]
 [4 3 2 1 2]
 [5 4 3 2 1]]


###Question 4. What is the inverse of matrix C? Show your solution by python coding. (20 points)

In [20]:
C = np.array ([[1,2,3],[2,3,3],[3,4,-2]]) #Matrix C
print(C) #to display or print

invC = np.linalg.inv(C) #Way to Inverse Matrix C
#to display or print
print('Inverse of Matrix C')
print(invC) #prints the Inverse of Matrix C

[[ 1  2  3]
 [ 2  3  3]
 [ 3  4 -2]]
Inverse of Matrix C
[[-3.6  3.2 -0.6]
 [ 2.6 -2.2  0.6]
 [-0.2  0.4 -0.2]]


###Question 5. What is the determinant of the given matrix in Question 4? Show your solution by python coding. (20 points)

In [36]:
C = np.array ([[1,2,3],[2,3,3],[3,4,-2]]) #Create Matrix C
print(C)
determinantC = np.linalg.det(C) #Gives determinant of C
#to display or print the answer or determinant
print('Determinant of the Given Matrix in Q4: ')
print(determinantC)
print('Rounded Off Determinant of Matrix C')
print(round(determinantC)) #Rounded off Answer



[[ 1  2  3]
 [ 2  3  3]
 [ 3  4 -2]]
Determinant of the Given Matrix in Q4: 
5.000000000000001
Rounded Off Determinant of Matrix C
5


###Question 6. Find the roots of the linear equations by showing its python codes (30 points)

In [39]:
A = np.array([[5,4,1],[10,9,4],[10,13,15]]) #Creation of a 3x3 matrix named A, that contains the equation.
B = np.array([[[3.4],[8.8],[19.2]]]) #Creation of a 2x3 matrix named B, that contains the constants.

roots = np.linalg.inv(eq) @B #to find roots of Linear equation
#to print and display the output
print('Roots of the given linear equations:')
print(roots) #final answer

Roots of the given linear equations:
[[[0.2]
  [0.4]
  [0.8]]]
