<a href="https://colab.research.google.com/github/adriyennKB/Linear-Algebra-58019/blob/main/Pratical_Lab_Exam_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Practical Lab Exam 1

## Problem 1  
##a. AB
##b. D+D
##c. 2C



In [56]:
import numpy as np
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[1,2],[3,4],[5,6]]) 
C = np.array([[1,2,3],[4,5,6],[7,8,9]])
D = np.array([[1,2],[3,4]]) 

dotA= np.dot(A,B)
b = np.add(D,D)
c = 2*C

print('Problem1')
print("\nA.")
print(dotA)
print("\nB.")
print(b)
print("\nC.")
print(c)



Problem1

A.
[[22 28]
 [49 64]]

B.
[[2 4]
 [6 8]]

C.
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


##Problem 2

In [58]:
import numpy as np
X = np.array([5,3,-1])

print('Problem2\n')
print(X)
print('\nsize of array : ', X.size)
print('type of array', type(X))
print('shape of array: ', X.shape)
print('dimension of array:', X.ndim)

Problem2

[ 5  3 -1]

size of array :  3
type of array <class 'numpy.ndarray'>
shape of array:  (3,)
dimension of array: 1
