<a href="https://colab.research.google.com/github/adriyennKB/Linear-Algebra-58019/blob/main/Prelim_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Prelim Exam

####Question 1. (20 points) Create a 4 x 4 matrix whose diagonal elements are all one (1's). Name it as matrix "C". Show your solutions using Python codes and do not forget to label them on the Text Cell.

In [6]:
import numpy as np
#declare the value of what value that is needed in the said Matrix which are all 1
Z= np.array([1,1,1,1])
C=np.diag(Z) #declare for the contents of variable Z to be diagonal

print(C) #to display or print the matrix

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


####Question 2. (20 points) In relation to Question 1, show a solution that doubles all the values of each element. Show your solutions using Python codes and do not forget to label them on the Text Cell.

In [4]:
import numpy as np
Z= np.array([1,1,1,1])
C=np.diag(Z)

#there are a lot of ways to double the values of each elements.
#simply multiply the Matrix C to 2 so it will be doubled.
print(C*2) #to display or print the output

[[2 0 0 0]
 [0 2 0 0]
 [0 0 2 0]
 [0 0 0 2]]


####Question 3. (10 points) Find the cross-product of matrices, A = [2,7,4] and



In [5]:
import numpy as np
A= np.array([2,7,4])
B= np.array([3,9,8])

#To compute the cross of A and B this will be used
CrossAB= np.cross(A,B)
print(CrossAB) #to display or print the output

[20 -4 -3]
