<a href="https://colab.research.google.com/github/adriyennKB/Linear-Algebra-58019/blob/main/PythonExercise1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Matrix and Its Operation

1. sum= A + B

In [6]:
#numpy
import numpy as np
A = np.array([[-5,0],[4,1]])
B = np.array([[6,-3],[2,3]])
print(A+B)

[[ 1 -3]
 [ 6  4]]


2. difference1= B-A

In [8]:
import numpy as np
A = np.array([[-5,0],[4,1]])
B = np.array([[6,-3],[2,3]])
print(B-A)

[[11 -3]
 [-2  2]]


3. difference2= A-B

In [10]:
import numpy as np
A = np.array([[-5,0],[4,1]])
B = np.array([[6,-3],[2,3]])
print(A-B)

[[-11   3]
 [  2  -2]]
