<a href="https://colab.research.google.com/github/adriyennKB/Linear-Algebra-58019/blob/main/Python_Exercise_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Vector Space Operations

##Representing Vectors

In [4]:
import numpy as np
A = np.array([4,3])
B = np.array([2,-5])
print('Vector A is', A)
print('Vector B is' , B)

Vector A is [4 3]
Vector B is [ 2 -5]


##Describing Vectors in Numpy

In [10]:
###Checking shapes
###Shapes tells us how many rows and columns are there

import numpy as np
ball1= np.array([1,2,3])
ball2= np.array([0,1,-1])
pool = np.array([ball1,ball2])
pool.shape


(2, 3)

In [11]:
###Checking shapes
###Shapes tells us how many rows and columns are there

import numpy as np
ball1= np.array([1,2,3])
ball2= np.array([0,1,-1])
pool = np.array([ball1,ball2])
pool.shape
pool.ndim

2

In [14]:
U= np.array(([1,2,3],[4,5,6]))
U

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
U= np.array(([1,2,3],[4,5,6]))
U.shape

(2, 3)

In [16]:
U= np.array(([1,2,3],[4,5,6]))
U.ndim

2

In [17]:
U= np.array(([1,2,3],[4,5,6]))
U.size

6

##Space

##Vector spaces are mathematical objects that abstractly capture the geometry and algebra of linear equations

###Addition of Vectors

In [22]:
addend1= np.array([0,0,0])
addend2= np.array([1,1,0])
sum= addend1 + addend2
sum

array([1, 1, 0])

In [26]:
addend1= np.array([0,0,0])
addend2= np.array([1,1,0])
resultant= np.add(addend1,addend2)
resultant

array([1, 1, 0])

###Subtraction of Vector

In [28]:
addend1= np.array([0,0,0])
addend2= np.array([1,1,0])
diff= addend1 - addend2
diff

array([-1, -1,  0])

###Multiplication of Vector

In [31]:
A= np.array([1,5,8,9])
S= 5*A
S

array([ 5, 25, 40, 45])

###Cross Product

In [35]:
import numpy as np
c
output= np.cross(A,B)
output


array(11)

In [36]:
import numpy as np
A = np.array([2,3,4])
B = np.array([1,7,1])
output= np.cross(A,B)
output

array([-25,   2,  11])

In [37]:
import numpy as np
A = np.array([2,3])
B = np.array([1,7])
dot= np.dot(A,B)
dot

23